### PR TITLE
New experiment for Rebuttal

### PR DESCRIPTION
**Pull request by pnkraemer**

### CODE REVIEW

**Comment by nathanaelbosch** [comment]
Can this just be merged, or do we need a detailed review of what's happenng here?

**Comment by pnkraemer** [comment]
Should be fine. The initialisation benchmark is not relevant, no idea why I left it in here :shrug: (maybe we kick it before public) But the other script is the rebuttal one.

If you want me to kick the initialisation script, I can do so in the next days :)

**Comment by nathanaelbosch** [comment]
Yes maybe it would be good to only merge the stuff that we want to have in the public version :)

**Comment by pnkraemer** [comment]
Done.

**Review by nathanaelbosch — APPROVED** [review]

**Pull request merged**
